services:   
  fluffychat:
    image: ghcr.io/krille-chan/fluffychat:latest
    container_name: fluffychat
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: 3